### ISSUE TITLE
Colour Changer Submission

### ISSUE THREAD

**Issue by dominichayesferen** [germanfr/railway-cinnamon#2]
What this script does:
When CDd into a folder with the 'Railway' Cinnamon theme in the directory, it will give you the option to set the main colour code to another colour tag of your choice, and then save it to ~/.themes/RailwayColourCodeHere

UPDATED: 
[Railway Colouring.sh.zip](https://github.com/germanfr/railway-cinnamon/files/1117053/Railway.Colouring.sh.zip)

**Comment by feren** [comment]
@germanfr

**Comment by germanfr** [comment]
Hey thank you. I already have an implementation for this, but I didn't push it.

Oops I deleted the mention.

**Comment by dominichayesferen** [comment]
Your welcome, also, this one's a bit more graphical
To-do:
- Give the user the choice of the product theme name
- Colour Picker Dialog instead of just a "Enter Colour Code Here" dialog

**Comment by dominichayesferen** [comment]
Ok, Updated it to give those missing features:
[Railway Colouring.sh.zip](https://github.com/germanfr/railway-cinnamon/files/1117859/Railway.Colouring.sh.zip)

**Comment by dominichayesferen** [comment]
Also, a little screenshot of what I came up with using the tool:
![screenshot from 2017-07-02 16-46-16](https://user-images.githubusercontent.com/11057934/27771419-feb1f1ac-5f45-11e7-98f8-74dbae95ec4b.png)

PS: Your theme does wonders when it's colourable!

**Comment by ayanb1991** [comment]
What's the gtk theme in the above preview. I need a door8 style gtk theme too to match with this cinnamon theme.

**Comment by dominichayesferen** [comment]
@ayanb1991 Windows8 (It's on GNOME Look, and OMG! Ubuntu's Article on making Ubuntu look like Windows 8.)

**Comment by pauloimon** [comment]
@feren Thank you!! Very nice tool!!

**Comment by germanfr** [comment]
I've finally implemented this feature in the installation script. 
All you have to do is run `make color=COLOR` and then `make install` to automatically install it or copy the theme manually into the theme folder.
