### ISSUE TITLE
Question: All colors in Cinnamon Spices

### ISSUE THREAD

**Issue by sidorsett** [germanfr/railway-cinnamon#4]
Hi, Germán.

Why don't you make all color alternatives available through Cinnamon Spices? They all deserve it!

Cheers.

**Comment by germanfr** [comment]
The colors in the screenshot are just examples. One can pick any color they want. There is not a fixed set of colors. 
Also in my experience, if one wants more colors it won't stop there, so at the end it is easier having a copy of the repo and running make color=#COLOR each time.

Anyways, I no longer have Cinnamon installed, so I won't be able to develop new features. I'll leave this open in case anyone or myself in the future wants to implement this. Thanks!
