### ISSUE TITLE
Feature request: Transparency changer

### ISSUE THREAD

**Issue by sidorsett** [germanfr/railway-cinnamon#5]
Hi, @germanfr 

In #2, you implemented the installation script with the `color` option. Would it be also possible to add a `transparency` option. You can make it as a simple `true`/`false` option, or as a percentage, if you want to add even more flexibility.

Railway is the best cinnamon theme. Thanks for creating it!

Cheers!

**Comment by germanfr** [comment]
There is an option in the sass files to compile the theme without transparency. It is ignored by the install script though. I don't currently have installed Cinnamon, so I can't develop new features. You can tweak that file before running the install script. Hope it helps!

The options file:
https://github.com/germanfr/railway-cinnamon/blob/master/Railway/cinnamon/scss/base/_options.scss

**Comment by sidorsett** [comment]
Wonderful! Thanks for the quick response, Germán.

As a memo for anybody willing to have opaque panel besides opaque menus.

It is necessary to modify the file:
https://github.com/germanfr/railway-cinnamon/blob/master/Railway/cinnamon/scss/base/_colors.scss

and add this line within the `if` statement at line 35:
```	$accent-element-panel: $theme-color;```

Cheers!
